import catImage from "../assets/HeroStaticResources/AboutUsHeroBackground.PNG"

export const volunteeringData = [
  {
    id: "1",
    image: catImage,
    category: "Feeding",
    shelterName: { name: "Casa Felina BCN", logo: "https://i.pravatar.cc/40?img=1" },
    name: "Cat Feeding & Care Support",
    location: "Barcelona",
    date: "12/8/2026",
    duration: "Domingos 09:00 - 12:00",
    availableSpaces: 2,
    totalSpaces: 8,
  },
  {
    id: "2",
    image: catImage,
    category: "Cleaning",
    shelterName: { name: "Safe Paws Shelter", logo: "https://i.pravatar.cc/40?img=2" },
    name: "Shelter Cleaning & Maintenance",
    location: "Madrid",
    date: "20/8/2026",
    duration: "Weekdays 10:00 - 14:00",
    availableSpaces: 4,
    totalSpaces: 7,
  },
  {
    id: "3",
    image: catImage,
    category: "Transport",
    shelterName: { name: "Gatitos en Adopción", logo: "https://i.pravatar.cc/40?img=3" },
    name: "Cat Transport to Veterinary Clinics",
    location: "Valencia",
    date: "5/9/2026",
    duration: "Sábados 10:00 - 13:00",
    availableSpaces: 3,
    totalSpaces: 4,
  },
  {
    id: "4",
    image: catImage,
    category: "Feeding",
    shelterName: { name: "Refugi Gat Feliç", logo: "https://i.pravatar.cc/40?img=4" },
    name: "Daily Feeding & Socialisation",
    location: "Barcelona",
    date: "15/8/2026",
    duration: "Lunes y miércoles 08:00 - 10:00",
    availableSpaces: 1,
    totalSpaces: 5,
  },
  {
    id: "5",
    image: catImage,
    category: "Cleaning",
    shelterName: { name: "Happy Paws Shelter", logo: "https://i.pravatar.cc/40?img=5" },
    name: "Enclosure Cleaning & Disinfection",
    location: "Sevilla",
    date: "22/8/2026",
    duration: "Viernes 09:00 - 12:00",
    availableSpaces: 5,
    totalSpaces: 6,
  },
  {
    id: "6",
    image: catImage,
    category: "Adoption",
    shelterName: { name: "Michi Rescue", logo: "https://i.pravatar.cc/40?img=6" },
    name: "Adoption Day Assistance",
    location: "Madrid",
    date: "30/8/2026",
    duration: "Sábado 10:00 - 15:00",
    availableSpaces: 6,
    totalSpaces: 8,
  },
]
